server:
  port: 8086

spring:
  application:
    name: uav-registry
  datasource:
    url: jdbc:postgresql://${DB_HOST:172.27.19.223}:${DB_PORT:5432}/${DB_NAME:uav_ams}
    username: ${DB_USER:uav}
    password: ${DB_PASS:uav123}
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.uav.registry: DEBUG
