server:
  port: 8085

spring:
  application:
    name: uav-airspace
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:uav_ams}
    username: ${DB_USER:uav}
    password: ${DB_PASS:uav123}
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  type-aliases-package: com.uav.airspace.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.uav.airspace: DEBUG
